import { Post } from "@/models/Post";
import axios from "axios"
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Home Page",
  description: "Generated by create next app",
};


export default async function Home() {

  const response = await axios.get('https://jsonplaceholder.typicode.com/commnts');

  const posts: Post[] = response.data;


  return (
    <div>
        {posts.map((post) => (
        <div key={post.id}>
          <h1>{post.name}</h1>
          <p>{post.email}</p>
          <p>{post.body}</p>
        </div>
      ))}

    </div>
  )
}