import { Metadata } from "next";
// import axios from "axios";

export const metadata: Metadata = {
  title: "Home Page",
  description: "Generated by create next app",
};

const Home = () => {

  // const response = await axios.get('https://jsonplaceholder.typicode.com/comments');

  // const posts: Post[] = response.data;
  return (
    <div>
      
    </div>
  )
}

export default Home
